export type FabricTable = {
  id: string;
  tableName: string;
  server: string;
  warehouse: string;
  SLADelayThreshold: string;
  DataObjectUTCAdjustment: string;
  IsDQA: boolean;
  FirstDataDate: string;
  AvailabilityDate: string;
  DataTags: string[];
  Comment: string;
  LastRefresh: string;
  RowCount: string;
  DataOwner: string;
  SourceSystem: string;
  StorageSize: string;
  slaStatus: "within" | "near" | "breached";
};

export type FabricWarehouse = {
  name: string;
  tables: FabricTable[];
};

export type FabricServer = {
  name: string;
  warehouses: FabricWarehouse[];
};

export type FabricCatalogData = {
  servers: FabricServer[];
};

function tableRecord(config: FabricTable): FabricTable {
  return config;
}

export const fabricCatalogData: FabricCatalogData = {
  servers: [
    {
      name: "Fabric-Prod",
      warehouses: [
        {
          name: "PlayerAnalyticsWarehouse",
          tables: [
            tableRecord({
              id: "paw-1",
              tableName: "PlayerActivity",
              server: "Fabric-Prod",
              warehouse: "PlayerAnalyticsWarehouse",
              SLADelayThreshold: "15 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-01-05",
              AvailabilityDate: "T+10 min",
              DataTags: ["Gaming", "UserBehavior"],
              Comment: "Core player activity stream consolidated by region.",
              LastRefresh: "2026-03-09 17:35 UTC",
              RowCount: "184,522,993",
              DataOwner: "Data Platform Ops",
              SourceSystem: "GameplayTelemetry",
              StorageSize: "1.9 TB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "paw-2",
              tableName: "PlayerTransactions",
              server: "Fabric-Prod",
              warehouse: "PlayerAnalyticsWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-11-11",
              AvailabilityDate: "T+15 min",
              DataTags: ["Finance", "Gaming", "Payments"],
              Comment:
                "Purchase and wallet events with fraud suppression flags.",
              LastRefresh: "2026-03-09 17:28 UTC",
              RowCount: "72,014,113",
              DataOwner: "Commercial Data Team",
              SourceSystem: "WalletCore",
              StorageSize: "812 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "paw-3",
              tableName: "GameSessions",
              server: "Fabric-Prod",
              warehouse: "PlayerAnalyticsWarehouse",
              SLADelayThreshold: "15 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-02-20",
              AvailabilityDate: "T+10 min",
              DataTags: ["Gaming", "UserBehavior"],
              Comment: "Session lifecycle facts for engagement dashboards.",
              LastRefresh: "2026-03-09 17:36 UTC",
              RowCount: "243,441,621",
              DataOwner: "Player Insights",
              SourceSystem: "SessionService",
              StorageSize: "2.6 TB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "paw-4",
              tableName: "RetentionCohorts",
              server: "Fabric-Prod",
              warehouse: "PlayerAnalyticsWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2022-04-12",
              AvailabilityDate: "T+25 min",
              DataTags: ["Gaming", "Marketing", "UserBehavior"],
              Comment: "Daily and weekly retention cut by product and channel.",
              LastRefresh: "2026-03-09 17:15 UTC",
              RowCount: "14,992,117",
              DataOwner: "Lifecycle Analytics",
              SourceSystem: "EngagementModel",
              StorageSize: "228 GB",
              slaStatus: "within",
            }),
          ],
        },
        {
          name: "FinanceWarehouse",
          tables: [
            tableRecord({
              id: "fin-1",
              tableName: "RevenueLedger",
              server: "Fabric-Prod",
              warehouse: "FinanceWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-01-01",
              AvailabilityDate: "T+20 min",
              DataTags: ["Finance", "Payments"],
              Comment: "Recognized revenue entries aligned to fiscal calendar.",
              LastRefresh: "2026-03-09 17:20 UTC",
              RowCount: "38,224,902",
              DataOwner: "Group Finance BI",
              SourceSystem: "ERP-Finance",
              StorageSize: "464 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "fin-2",
              tableName: "CostOfSales",
              server: "Fabric-Prod",
              warehouse: "FinanceWarehouse",
              SLADelayThreshold: "45 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-01-01",
              AvailabilityDate: "T+30 min",
              DataTags: ["Finance"],
              Comment: "Cost postings for margin and contribution reporting.",
              LastRefresh: "2026-03-09 16:55 UTC",
              RowCount: "11,771,209",
              DataOwner: "FP&A Platform",
              SourceSystem: "ERP-Controlling",
              StorageSize: "179 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "fin-3",
              tableName: "BudgetForecast",
              server: "Fabric-Prod",
              warehouse: "FinanceWarehouse",
              SLADelayThreshold: "60 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2021-07-01",
              AvailabilityDate: "T+45 min",
              DataTags: ["Finance", "Risk"],
              Comment: "Rolling forecast snapshots by entity and scenario.",
              LastRefresh: "2026-03-09 16:40 UTC",
              RowCount: "3,603,442",
              DataOwner: "Corporate Planning",
              SourceSystem: "PlanningSuite",
              StorageSize: "61 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "fin-4",
              tableName: "TaxExposure",
              server: "Fabric-Prod",
              warehouse: "FinanceWarehouse",
              SLADelayThreshold: "60 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-03-17",
              AvailabilityDate: "T+50 min",
              DataTags: ["Finance", "Risk"],
              Comment: "Tax liability and jurisdictional exposure positions.",
              LastRefresh: "2026-03-09 15:58 UTC",
              RowCount: "2,118,301",
              DataOwner: "Tax Reporting",
              SourceSystem: "GlobalTaxHub",
              StorageSize: "38 GB",
              slaStatus: "breached",
            }),
          ],
        },
        {
          name: "PaymentsWarehouse",
          tables: [
            tableRecord({
              id: "pay-1",
              tableName: "PaymentAuthorizations",
              server: "Fabric-Prod",
              warehouse: "PaymentsWarehouse",
              SLADelayThreshold: "10 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-09-04",
              AvailabilityDate: "T+5 min",
              DataTags: ["Payments", "Risk"],
              Comment: "Authorization outcomes and acquirer response details.",
              LastRefresh: "2026-03-09 17:37 UTC",
              RowCount: "312,998,774",
              DataOwner: "Payments Engineering",
              SourceSystem: "GatewayMesh",
              StorageSize: "3.1 TB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "pay-2",
              tableName: "Chargebacks",
              server: "Fabric-Prod",
              warehouse: "PaymentsWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-10-01",
              AvailabilityDate: "T+20 min",
              DataTags: ["Payments", "Finance", "Risk"],
              Comment: "Chargeback events and recovery lifecycle states.",
              LastRefresh: "2026-03-09 17:09 UTC",
              RowCount: "8,129,551",
              DataOwner: "Payments Risk",
              SourceSystem: "DisputeCenter",
              StorageSize: "121 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "pay-3",
              tableName: "SettlementBatches",
              server: "Fabric-Prod",
              warehouse: "PaymentsWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2021-09-15",
              AvailabilityDate: "T+15 min",
              DataTags: ["Payments", "Finance"],
              Comment: "Daily settlement batches normalized across providers.",
              LastRefresh: "2026-03-09 16:52 UTC",
              RowCount: "5,770,991",
              DataOwner: "Treasury Data",
              SourceSystem: "SettlementOps",
              StorageSize: "88 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "pay-4",
              tableName: "FraudSignals",
              server: "Fabric-Prod",
              warehouse: "PaymentsWarehouse",
              SLADelayThreshold: "10 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-01-26",
              AvailabilityDate: "T+6 min",
              DataTags: ["Risk", "Payments"],
              Comment: "Low-latency fraud scoring features with model lineage.",
              LastRefresh: "2026-03-09 17:38 UTC",
              RowCount: "488,002,144",
              DataOwner: "Fraud Intelligence",
              SourceSystem: "FraudML",
              StorageSize: "4.4 TB",
              slaStatus: "within",
            }),
          ],
        },
        {
          name: "OperationsWarehouse",
          tables: [
            tableRecord({
              id: "ops-1",
              tableName: "IncidentLog",
              server: "Fabric-Prod",
              warehouse: "OperationsWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2022-06-01",
              AvailabilityDate: "T+12 min",
              DataTags: ["Risk"],
              Comment:
                "Operational incidents with severity and assignment trail.",
              LastRefresh: "2026-03-09 17:18 UTC",
              RowCount: "1,207,811",
              DataOwner: "Platform Reliability",
              SourceSystem: "ServiceDesk",
              StorageSize: "17 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "ops-2",
              tableName: "ReleaseCalendar",
              server: "Fabric-Prod",
              warehouse: "OperationsWarehouse",
              SLADelayThreshold: "60 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2023-01-02",
              AvailabilityDate: "T+40 min",
              DataTags: ["UserBehavior"],
              Comment: "Planned and completed release milestones by squad.",
              LastRefresh: "2026-03-09 16:22 UTC",
              RowCount: "94,110",
              DataOwner: "Engineering PMO",
              SourceSystem: "ReleaseHub",
              StorageSize: "2.1 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "ops-3",
              tableName: "ResourceUtilization",
              server: "Fabric-Prod",
              warehouse: "OperationsWarehouse",
              SLADelayThreshold: "15 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-08-08",
              AvailabilityDate: "T+10 min",
              DataTags: ["Finance", "Risk"],
              Comment: "Compute and storage usage telemetry by domain.",
              LastRefresh: "2026-03-09 16:57 UTC",
              RowCount: "18,621,550",
              DataOwner: "FinOps",
              SourceSystem: "InfraMetrics",
              StorageSize: "245 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "ops-4",
              tableName: "SupportQueue",
              server: "Fabric-Prod",
              warehouse: "OperationsWarehouse",
              SLADelayThreshold: "25 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-06-19",
              AvailabilityDate: "T+15 min",
              DataTags: ["UserBehavior", "Marketing"],
              Comment: "Support backlog and response SLA metrics.",
              LastRefresh: "2026-03-09 17:03 UTC",
              RowCount: "9,994,408",
              DataOwner: "Customer Operations",
              SourceSystem: "CRM-Support",
              StorageSize: "131 GB",
              slaStatus: "within",
            }),
          ],
        },
      ],
    },
    {
      name: "Fabric-Analytics",
      warehouses: [
        {
          name: "MarketingWarehouse",
          tables: [
            tableRecord({
              id: "mkt-1",
              tableName: "CampaignPerformance",
              server: "Fabric-Analytics",
              warehouse: "MarketingWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-05-10",
              AvailabilityDate: "T+20 min",
              DataTags: ["Marketing"],
              Comment:
                "Cross-channel campaign facts at daily and intraday granularity.",
              LastRefresh: "2026-03-09 17:01 UTC",
              RowCount: "27,771,188",
              DataOwner: "Marketing Insights",
              SourceSystem: "AdManager",
              StorageSize: "302 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "mkt-2",
              tableName: "AttributionModel",
              server: "Fabric-Analytics",
              warehouse: "MarketingWarehouse",
              SLADelayThreshold: "45 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2021-06-14",
              AvailabilityDate: "T+30 min",
              DataTags: ["Marketing", "Finance"],
              Comment: "Touchpoint attribution outcomes by model version.",
              LastRefresh: "2026-03-09 16:30 UTC",
              RowCount: "6,250,004",
              DataOwner: "Performance Marketing",
              SourceSystem: "AttributionLab",
              StorageSize: "78 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "mkt-3",
              tableName: "AudienceSegments",
              server: "Fabric-Analytics",
              warehouse: "MarketingWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-09-01",
              AvailabilityDate: "T+15 min",
              DataTags: ["Marketing", "UserBehavior"],
              Comment:
                "Curated segments synchronized with activation platforms.",
              LastRefresh: "2026-03-09 17:16 UTC",
              RowCount: "45,883,307",
              DataOwner: "Audience Platform",
              SourceSystem: "CDP-Core",
              StorageSize: "514 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "mkt-4",
              tableName: "PromoRedemptions",
              server: "Fabric-Analytics",
              warehouse: "MarketingWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-10-11",
              AvailabilityDate: "T+20 min",
              DataTags: ["Marketing", "Payments"],
              Comment:
                "Promotion redemption rates across channels and cohorts.",
              LastRefresh: "2026-03-09 16:11 UTC",
              RowCount: "4,118,450",
              DataOwner: "CRM Analytics",
              SourceSystem: "PromotionEngine",
              StorageSize: "66 GB",
              slaStatus: "breached",
            }),
          ],
        },
        {
          name: "RiskWarehouse",
          tables: [
            tableRecord({
              id: "rsk-1",
              tableName: "KycChecks",
              server: "Fabric-Analytics",
              warehouse: "RiskWarehouse",
              SLADelayThreshold: "15 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-08-08",
              AvailabilityDate: "T+10 min",
              DataTags: ["Risk", "UserBehavior"],
              Comment: "Identity verification outcomes with retry history.",
              LastRefresh: "2026-03-09 17:27 UTC",
              RowCount: "33,991,225",
              DataOwner: "Trust & Safety",
              SourceSystem: "KYCProviderHub",
              StorageSize: "403 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "rsk-2",
              tableName: "RiskScores",
              server: "Fabric-Analytics",
              warehouse: "RiskWarehouse",
              SLADelayThreshold: "10 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-09-03",
              AvailabilityDate: "T+8 min",
              DataTags: ["Risk", "Payments"],
              Comment:
                "Unified risk score outputs with model explainability vectors.",
              LastRefresh: "2026-03-09 17:34 UTC",
              RowCount: "402,221,920",
              DataOwner: "Decision Science",
              SourceSystem: "RiskEngine",
              StorageSize: "3.7 TB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "rsk-3",
              tableName: "AMLAlerts",
              server: "Fabric-Analytics",
              warehouse: "RiskWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2021-12-13",
              AvailabilityDate: "T+14 min",
              DataTags: ["Risk", "Finance"],
              Comment: "AML signal events and analyst case progression.",
              LastRefresh: "2026-03-09 16:59 UTC",
              RowCount: "12,880,301",
              DataOwner: "Compliance Analytics",
              SourceSystem: "AMLMonitor",
              StorageSize: "155 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "rsk-4",
              tableName: "RegulatoryEvents",
              server: "Fabric-Analytics",
              warehouse: "RiskWarehouse",
              SLADelayThreshold: "60 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-02-07",
              AvailabilityDate: "T+50 min",
              DataTags: ["Risk", "Finance"],
              Comment:
                "Regulatory filing events and control evidence metadata.",
              LastRefresh: "2026-03-09 16:03 UTC",
              RowCount: "1,331,050",
              DataOwner: "Regulatory Reporting",
              SourceSystem: "GovControl",
              StorageSize: "21 GB",
              slaStatus: "breached",
            }),
          ],
        },
        {
          name: "CustomerInsightsWarehouse",
          tables: [
            tableRecord({
              id: "ci-1",
              tableName: "PlayerProfiles",
              server: "Fabric-Analytics",
              warehouse: "CustomerInsightsWarehouse",
              SLADelayThreshold: "25 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-04-01",
              AvailabilityDate: "T+18 min",
              DataTags: ["UserBehavior", "Gaming"],
              Comment:
                "Golden player profile with consent and preference facets.",
              LastRefresh: "2026-03-09 17:10 UTC",
              RowCount: "58,110,980",
              DataOwner: "Customer Intelligence",
              SourceSystem: "MDM-Core",
              StorageSize: "689 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "ci-2",
              tableName: "LifecycleEvents",
              server: "Fabric-Analytics",
              warehouse: "CustomerInsightsWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2021-05-09",
              AvailabilityDate: "T+15 min",
              DataTags: ["UserBehavior", "Marketing"],
              Comment:
                "Lifecycle state transitions used for trigger automation.",
              LastRefresh: "2026-03-09 17:14 UTC",
              RowCount: "96,204,712",
              DataOwner: "Retention Science",
              SourceSystem: "JourneyOrchestrator",
              StorageSize: "1.1 TB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "ci-3",
              tableName: "VipSegments",
              server: "Fabric-Analytics",
              warehouse: "CustomerInsightsWarehouse",
              SLADelayThreshold: "40 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2022-01-19",
              AvailabilityDate: "T+30 min",
              DataTags: ["Marketing", "Finance", "Gaming"],
              Comment: "VIP tiering outcomes for value management teams.",
              LastRefresh: "2026-03-09 16:35 UTC",
              RowCount: "2,910,420",
              DataOwner: "VIP Commercial",
              SourceSystem: "VIPWorkbench",
              StorageSize: "48 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "ci-4",
              tableName: "ChurnPredictions",
              server: "Fabric-Analytics",
              warehouse: "CustomerInsightsWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2022-11-03",
              AvailabilityDate: "T+20 min",
              DataTags: ["UserBehavior", "Marketing", "Risk"],
              Comment: "Daily churn propensity scores and feature importance.",
              LastRefresh: "2026-03-09 16:50 UTC",
              RowCount: "14,415,338",
              DataOwner: "Data Science Ops",
              SourceSystem: "MLServing",
              StorageSize: "194 GB",
              slaStatus: "near",
            }),
          ],
        },
      ],
    },
    {
      name: "Fabric-Dev",
      warehouses: [
        {
          name: "SandboxWarehouse",
          tables: [
            tableRecord({
              id: "sbx-1",
              tableName: "PrototypeEvents",
              server: "Fabric-Dev",
              warehouse: "SandboxWarehouse",
              SLADelayThreshold: "120 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2024-01-10",
              AvailabilityDate: "T+90 min",
              DataTags: ["UserBehavior"],
              Comment: "Experimental event stream for feature prototyping.",
              LastRefresh: "2026-03-09 15:41 UTC",
              RowCount: "822,119",
              DataOwner: "Innovation Lab",
              SourceSystem: "SandboxTelemetry",
              StorageSize: "11 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "sbx-2",
              tableName: "DevTransactionMocks",
              server: "Fabric-Dev",
              warehouse: "SandboxWarehouse",
              SLADelayThreshold: "180 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2024-02-01",
              AvailabilityDate: "T+120 min",
              DataTags: ["Payments", "Finance"],
              Comment:
                "Synthetic payment transaction data for integration tests.",
              LastRefresh: "2026-03-09 14:18 UTC",
              RowCount: "1,442,093",
              DataOwner: "Platform QA",
              SourceSystem: "MockFactory",
              StorageSize: "19 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "sbx-3",
              tableName: "FeatureFlagsHistory",
              server: "Fabric-Dev",
              warehouse: "SandboxWarehouse",
              SLADelayThreshold: "90 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2024-03-12",
              AvailabilityDate: "T+70 min",
              DataTags: ["Risk", "UserBehavior"],
              Comment: "Feature flag evaluations and rollout diagnostics.",
              LastRefresh: "2026-03-09 15:10 UTC",
              RowCount: "3,102,288",
              DataOwner: "Developer Experience",
              SourceSystem: "FlagService",
              StorageSize: "34 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "sbx-4",
              tableName: "UITestTelemetry",
              server: "Fabric-Dev",
              warehouse: "SandboxWarehouse",
              SLADelayThreshold: "120 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2024-04-04",
              AvailabilityDate: "T+100 min",
              DataTags: ["Marketing", "Gaming"],
              Comment: "UI automation telemetry to benchmark release quality.",
              LastRefresh: "2026-03-09 13:50 UTC",
              RowCount: "711,803",
              DataOwner: "QA Engineering",
              SourceSystem: "UITestCloud",
              StorageSize: "9 GB",
              slaStatus: "breached",
            }),
          ],
        },
        {
          name: "InnovationWarehouse",
          tables: [
            tableRecord({
              id: "inn-1",
              tableName: "LLMFeatureUsage",
              server: "Fabric-Dev",
              warehouse: "InnovationWarehouse",
              SLADelayThreshold: "60 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2025-01-15",
              AvailabilityDate: "T+45 min",
              DataTags: ["UserBehavior", "Marketing"],
              Comment: "Usage telemetry for AI-assisted product capabilities.",
              LastRefresh: "2026-03-09 16:08 UTC",
              RowCount: "4,091,011",
              DataOwner: "AI Product Analytics",
              SourceSystem: "PromptGateway",
              StorageSize: "52 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "inn-2",
              tableName: "RealtimeExperimentMetrics",
              server: "Fabric-Dev",
              warehouse: "InnovationWarehouse",
              SLADelayThreshold: "30 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2025-02-02",
              AvailabilityDate: "T+20 min",
              DataTags: ["Gaming", "Marketing", "UserBehavior"],
              Comment:
                "Experiment metrics for realtime personalization pilots.",
              LastRefresh: "2026-03-09 16:44 UTC",
              RowCount: "8,449,223",
              DataOwner: "Experimentation Team",
              SourceSystem: "ExperimentHub",
              StorageSize: "97 GB",
              slaStatus: "within",
            }),
            tableRecord({
              id: "inn-3",
              tableName: "StreamingModelFeatures",
              server: "Fabric-Dev",
              warehouse: "InnovationWarehouse",
              SLADelayThreshold: "20 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: true,
              FirstDataDate: "2025-03-06",
              AvailabilityDate: "T+15 min",
              DataTags: ["Risk", "Payments", "Gaming"],
              Comment:
                "Streaming features used by low-latency decision models.",
              LastRefresh: "2026-03-09 16:32 UTC",
              RowCount: "21,118,991",
              DataOwner: "Applied ML",
              SourceSystem: "FeatureStore",
              StorageSize: "261 GB",
              slaStatus: "near",
            }),
            tableRecord({
              id: "inn-4",
              tableName: "SyntheticPlayerTwin",
              server: "Fabric-Dev",
              warehouse: "InnovationWarehouse",
              SLADelayThreshold: "90 min",
              DataObjectUTCAdjustment: "+00:00",
              IsDQA: false,
              FirstDataDate: "2025-04-21",
              AvailabilityDate: "T+60 min",
              DataTags: ["Gaming", "Finance"],
              Comment:
                "Digital twin simulation dataset for product strategy testing.",
              LastRefresh: "2026-03-09 15:27 UTC",
              RowCount: "1,090,230",
              DataOwner: "Simulation Lab",
              SourceSystem: "TwinEngine",
              StorageSize: "16 GB",
              slaStatus: "within",
            }),
          ],
        },
      ],
    },
  ],
};
